ALTER TABLE ratings PARTITION BY RANGE(movieId) (
          PARTITION p0 VALUES LESS THAN (356),
          PARTITION p1 VALUES LESS THAN (898),
          PARTITION p2 VALUES LESS THAN (1295),
          PARTITION p3 VALUES LESS THAN (2081),
          PARTITION p4 VALUES LESS THAN (2947),
          PARTITION p5 VALUES LESS THAN (4148),
          PARTITION p6 VALUES LESS THAN (6478),
          PARTITION p7 VALUES LESS THAN (44191),
          PARTITION p8 VALUES LESS THAN (81847),
          PARTITION p9 VALUES LESS THAN (209172)
);